name: movemate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.0.15

  carousel_slider: ^4.0.0

  # Intro
  # intro_screen_onboarding_flutter: ^1.0.0

  # Router
  auto_route:
    ^7.8.4

    # Handle exception
  fpdart:
    ^1.1.0

    # Networking
  retrofit: ^4.0.3
  dio: ^5.4.0
  awesome_dio_interceptor: ^1.0.0

  #Icon
  icons_plus:
    ^4.0.0

    # Animation
  lottie: ^2.7.0
  flag: ^7.0.0
  font_awesome_flutter: ^10.6.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

# config native splash
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash/screen_splash.png
  android_12:
      image: assets/images/splash/screen_splash.png
    # background_image: assets/images/splash/splash.png
    # image: assets/images/splash/splash.png

# config launcher icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash/screen_splash.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test: 
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.6
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  plugin_platform_interface: ^2.1.7

flutter:

 
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/onboarding/onboarding1.png
    - assets/images/onboarding/onboarding2.png
    - assets/images/onboarding/onboarding3.png

    - assets/images/background/bg_1.jpg
    - assets/images/splash/screen_splash.png

    - assets/images/home/pexels-photoscom-933981.png
    - assets/images/home/vanchuyen1.png
    - assets/images/home/vanchuyen2.png
    - assets/images/home/vanchuyen3.png
    - assets/images/home/vanchuyen4.png
    - assets/images/home/Group18564.png
    - assets/images/home/image78.png
    - assets/images/home/image13.png
    - assets/images/promotion/Ellipse171.png
    - assets/images/profile/Image.png

    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
